import acneProven from './acneProven.png'
import antiAgingProven from './antiAgingProven.png'
import deepCleansingProven from './deepCleansingProven.png'
import jawlineProven from './jawlineProven.png'
import microneedlingProven from './microneedlingProven.png'
import profhiloProven from './profhiloProven.png'
import skinboosterProven from './skinboosterProven.png'
import vvpProven from './vvpProven.png'
import dermalFillersProven from './dermalFillersProven.png'
import crowFeetProven from './crowFeetProven.png'
import chemicalPeelProven from './chemicalPeelProven.png'
import foreheadLinesProven from './foreheadProven.png'
import underEyesProven from './underEyeProven.png'
import hydratingFacialProven from './hydratingFacialProven.png'
import prpProven from './prpProven.png'
import dermabrasionProven from './dermabrasionProven.png'
export { acneProven, antiAgingProven, deepCleansingProven, jawlineProven, microneedlingProven, profhiloProven, skinboosterProven, vvpProven, dermalFillersProven, crowFeetProven, chemicalPeelProven, foreheadLinesProven, underEyesProven, hydratingFacialProven, prpProven, dermabrasionProven }